### ISSUE TITLE
[FEATURE] Security Group redundant rule for 169.154.x.x

### ISSUE THREAD

**Issue by mehrajk** [aws-samples/sagemaker-studio-docker-cli-extension#6]
**Is your feature request related to a problem? Please describe.**
This tool (scdocker) creates a security group outbound rule to "allow outgoing traffic to 169.254.169.254 at port 80 (i.e instance metadata service)". This is a redundant security group rule. Security group implicitly allows this traffic described in the document https://docs.aws.amazon.com/vpc/latest/userguide/security-groups.html and no need to add such rule explicitly.
  The presence of such a security group rule is causing a false alarm with the (3rd party) security monitoring system and the customer has to take action to either manually remove this rule from the security group or use a workaround to provide their own custom security group without 169.254.169.254 based rule. This is creating an annoyance and unnecessary work for the customer security team.

**Describe the solution you'd like**
If it is not necessary to create  outbound  SG rule to "allow outgoing traffic to 169.254.169.254 at port 80 (i.e instance metadata service)", then remove such and update the document to remove 169.254.169.254 reference. The customer verified this tool works without such SG oubound rule. 

**Describe alternatives you've considered**
A workaround is to use custom security group without outbound  SG rule to "allow outgoing traffic to 169.254.169.254 at port 80 (i.e instance metadata service)". However, in a large environment educating team members takes extra effort and still getting false security alerts time to time.

**Additional context**

**Comment by samadwar** [comment]
Thank you for reporting this issue.

After testing, I was able to confirm such rule is not required. The code does not enforce this rule so fixing README.MD with this [commit](https://github.com/aws-samples/sagemaker-studio-docker-cli-extension/commit/0e4b9eb5a236cb1ac8488023e21c82b2b35fea6a) should be enough
